services:
  db:
    image: postgres:16
    container_name: api_crud_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api_crud
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d api_crud"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: .
    container_name: api_crud_api
    depends_on:
      db:
        condition: service_healthy
    environment:              
      PORT: "3000"
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/api_crud"
      DATABASE_SSL: "false"    
    ports:
      - "3000:3000"
    command: ["node", "src/server.js"]

volumes:
  pgdata:
